Rewritten the moderation commands
GetGravitySoft/VylBot pull request #117
Opened 2020-09-28 13:43 UTC by Vylpes

The commands now should be more reliable and cleaner. Also I have added comments to the files as well.

Closes #84

2020-09-30 13:55 UTC, VylpesTester requested changes

2020-09-30 13:55 UTC, VylpesTester commented on commands/ban.js
> +			let serverName = message.guild.name;
Unused variable

2020-09-30 13:55 UTC, VylpesTester commented on commands/kick.js
> +			let serverName = message.guild.name;
Unused variable

2020-09-30 13:55 UTC, VylpesTester commented on commands/mute.js
> +			let serverName = message.guild.name;
Unused variable

2020-09-30 13:55 UTC, VylpesTester commented on commands/unmute.js
> +			let serverName = message.guild.name;
Unused variable

2020-09-30 13:55 UTC, VylpesTester commented on commands/warn.js
> +			let serverName = message.guild.name;
Unused variable

2020-10-02 14:06 UTC, Simyon264 commented on commands/ban.js
> +								.setDescription("I am unable to ban this user. Am I missing permissions?");
Since this is with the `if (member.bannable) {` you could change that to _I am unable to ban this user. I'm missing permissions!_ this is true with kick, ban, mute and unmute. You dont have to change that but im still saying this ¯\_(ツ)_/¯

2020-10-02 14:10 UTC, Simyon264 commented on commands/unmute.js
> +								.setDescription("I am unable to mute this user. Am I missing permissions?");
This is _unmute_ not _mute_ _Ctrl + c_ and _Ctrl + v_ is not nice :vylAngry:

2020-10-02 14:14 UTC, Simyon264 commented on commands/warn.js
> +								.setDescription("I am unable to mute this user. Am I missing permissions?");
wat?

2020-10-02 14:23 UTC, Simyon264 approved these changes
everything works

2020-10-02 15:10 UTC, VylpesTester requested changes
Should also DM the user the reason for the moderation commands. Make sure to also use .catch() to get if it failed to DM (.then() is optional).

2020-10-02 15:10 UTC, VylpesTester commented on commands/mute.js
> +								.addField("Reason", reason || "*none*")
Should also DM the user the reason. Make sure to also use .catch() to get if it failed to DM (.then() is optional).

2020-10-02 15:10 UTC, VylpesTester commented on commands/warn.js
> +								.addField("Reason", reason || "*none*");
Should also DM the user the reason. Make sure to also use .catch() to get if it failed to DM (.then() is optional).

2020-10-03 22:12 UTC, merged