Vylpes/mode scripts
GetGravitySoft/VylBot pull request #97
Opened 2020-09-04 13:38 UTC by Vylpes

2020-09-06 13:46 UTC, Simyon264 requested changes
In message.js there is a console.log() that needs to be removed

2020-09-06 13:49 UTC, Simyon264 requested changes
The dev prefix is broken and wont work even if you start in dev mode

2020-09-06 14:06 UTC, Vylpes commented
> The dev prefix is broken and wont work even if you start in dev mode
@Simyon264 

Make sure that the dev prefix and dev token is supplied correctly in config.js
Also make sure that you're starting dev mode correctly using either `node bot.js -dev` or `npm run dev`

2020-09-07 09:43 UTC, VylpesTester approved these changes

2020-09-07 10:08 UTC, merged